CREATE TABLE IF NOT EXISTS yoda_db.YODA_USER (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(50),
    PASSWORD VARCHAR(50),
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30),
    DESCRIPTION VARCHAR(4000),
    PRIMARY KEY(USER_ID)
)

AUTO_INCREMENT = 10000;

CREATE TABLE IF NOT EXISTS yoda_db.COURSES (
    COURSE_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50),
    DESCRIPTION VARCHAR(4000),
    PRIMARY KEY (COURSE_ID)
)

AUTO_INCREMENT = 1000;

CREATE TABLE IF NOT EXISTS yoda_db.TUTORS (
    USER_ID INT,
    COURSE_ID INT,
    DESCRIPTION VARCHAR(4000),
    PRIMARY KEY(USER_ID, COURSE_ID),
    FOREIGN KEY (USER_ID) REFERENCES yoda_db.YODA_USER(USER_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES yoda_db.COURSES(COURSE_ID)
);

CREATE TABLE IF NOT EXISTS yoda_db.YODA_SESSION (
    SESSION_ID INT NOT NULL AUTO_INCREMENT,
    TUTOR_ID INT NOT NULL,
    TUTEE_ID INT NOT NULL,
    SCHEDULED_TIME TIMESTAMP,
    LOCATION VARCHAR(100),
    STATUS VARCHAR(30),
    EMAIL_SENT BIT DEFAULT 0,
    COURSE_ID INT NOT NULL,
    COUSRE_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (SESSION_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES yoda_db.COURSES(COURSE_ID),
    FOREIGN KEY (COURSE_NAME) REFERENCES yoda_db.COURSES(COURSE_NAME),
    FOREIGN KEY (TUTOR_ID) REFERENCES yoda_db.YODA_USER(USER_ID),
    FOREIGN KEY (TUTEE_ID) REFERENCES yoda_db.YODA_USER(USER_ID)
)

AUTO_INCREMENT = 100;

CREATE TABLE yoda_db.RATING (
    SESSION_ID INT,
    RATING INT,
    USER_COMMENT VARCHAR(4000),
    PRIMARY KEY (SESSION_ID),
    FOREIGN KEY (SESSION_ID) REFERENCES yoda_db.YODA_SESSION(SESSION_ID)
);
